# SPDX-FileCopyrightText: 2023 Nomadic Labs <contact@nomadic-labs.com>
# SPDX-FileCopyrightText: 2023 Marigold <contact@marigold.dev>
# SPDX-FileCopyrightText: 2023-2025 Functori <contact@functori.com>
# SPDX-FileCopyrightText: 2023 PK Lab <contact@pklab.io>
# SPDX-FileCopyrightText: 2024 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[workspace]
resolver = "2"

members = [
  "ethereum",
  "kernel",
  "evm_execution",
  "indexable_storage",
  "logging",
  "storage",
  "runtime",
]

[workspace.dependencies]

# error handling
thiserror = "1.0"
anyhow = "1.0"

# types
primitive-types = { version = "0.12.1", default-features = false }
num-bigint = { version = "0.4", default-features = false }
num-traits = "0.2.8"
num-derive = "0.4"
ethereum = { version = "0.14.0", default-features = false }
ethbloom = { version = "0.13.0", default-features = false, features = ["rlp"] }
softfloat = "1.0.0"
bytes = "^1"

# serialization
hex = "0.4"
hex-literal = "0.4.1"
tezos_data_encoding = { version = "0.6", git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
const-decoder = { version = "0.3.0" }
rlp = "0.5.2"

# ethereum VM
evm = { path = "../sputnikvm", default-features = false }
aurora-engine-modexp = { version = "1.0", default-features = false }
bn = { package = "substrate-bn", version = "0.6", default-features = false }

# crypto stuff
sha2 = { version = "0.10.6", default-features = false }
sha3 = { version = "0.10.6", default-features = false }
ripemd = { version = "0.1.3", default-features = false }
# TODO (SDK-45): bump to `0.6.1` from crates.io as soon as it is released.
tezos_crypto_rs = { version = "0.6", git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2", default-features = false }
libsecp256k1 = { version = "0.7", default-features = false, features = [
  "static-context",
  "hmac",
] }

# kernel crates
tezos_ethereum = { package = "tezos_ethereum_calypso2", path = "./ethereum" }
evm-execution = { package = "evm-execution-calypso2", path = "./evm_execution" }
tezos-evm-logging = { package = "tezos-evm-logging-calypso2", path = "./logging" }
tezos-evm-runtime = { package = "tezos-evm-runtime-calypso2", path = "./runtime" }
tezos-indexable-storage = { package = "tezos-indexable-storage-calypso2", path = "./indexable_storage" }
tezos-storage = { package = "tezos-storage-calypso2", path = "./storage" }

# SDK
# we disable BLS, because we donâ€™t need it and it is a roadblock for the native execution
tezos-smart-rollup = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2", default-features = false, features = [
  "std",
  "crypto",
  "dlmalloc",
  "panic-hook",
  "data-encoding",
  "storage",
  "testing",
] }
tezos-smart-rollup-core = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
tezos-smart-rollup-host = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
tezos-smart-rollup-panic-hook = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
tezos-smart-rollup-entrypoint = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
tezos-smart-rollup-debug = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
tezos-smart-rollup-encoding = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2", default-features = false, features = [
  "alloc",
  "tezos-encoding",
  "crypto",
] }
tezos-smart-rollup-installer-config = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
tezos-smart-rollup-mock = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
tezos-smart-rollup-storage = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }

# property based testing
rand = { version = "0.8" }
proptest = { version = "1.0" }
pretty_assertions = { version = "1.4.0" }

# alloy
alloy-sol-types = { version = "0.7.7", default-features = false, features = [
  "json",
] }
alloy-primitives = { version = "0.7.7", default-features = false }

[profile.release]
# Will apply heavy LTO which attempts to perform optimizations across all crates
# within the dependency graph.
lto = true
