# SPDX-FileCopyrightText: 2023 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos-smart-rollup-installer"
version = "0.1.0"
edition = "2021"
authors = ["TriliTech <contact@trili.tech>"]
include = [
  "build.rs",
  "src/*",
  "../installer_kernel/src/*",
  "../installer.wasm"
]

[[bin]]
name = "smart-rollup-installer"
path = "src/main.rs"

[dependencies.blst]
version = "0.3.10"
features = ["portable"]

[dependencies.tezos-smart-rollup-encoding]
path = "../encoding"

[dependencies.clap]
version = "4.1"
features = ["derive"]

[dependencies.hex]
version = "0.4"

[dependencies.thiserror]
version = "1.0"

[dependencies.wasm-gen]
version = "0.1.4"
