[package]
name = "risc-v-sandbox"
version = "0.0.0"
edition = "2021"

[dependencies]
goblin = "0.7.1"
derive_more = "0.99.17"
vm-fdt = "0.3.0"
tezos_crypto_rs = "0.5.2"

[dependencies.clap]
version = "4.4.6"
features = ["derive"]

[dependencies.kernel-loader]
version = "0.1.0"
path = "../kernel_loader"

[dependencies.rvemu]
git = "https://github.com/vapourismo/rvemu.git"
branch = "pub-translate"

[dependencies.tezos-smart-rollup-encoding]
path = "../../kernel_sdk/encoding"

[dependencies.tezos-smart-rollup-constants]
path = "../../kernel_sdk/constants"
