# SPDX-FileCopyrightText: 2022-2023 TriliTech <contact@trili.tech>
# SPDX-FileCopyrightText: 2023 Nomadic Labs <contact@nomadic-labs.com>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos-smart-rollup-entrypoint"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
dlmalloc = { version = "0.2.3", features = ["global"], optional = true}

[dependencies.tezos-smart-rollup-core]
path = "../core"
default-features = false

[dependencies.tezos-smart-rollup-panic-hook]
path = "../panic-hook"
default-features = false
optional = true

[dependencies.tezos-smart-rollup-host]
path = "../host"
default-features = false

[dependencies.tezos-smart-rollup-debug]
path = "../debug"
default-features = false

[features]
default = ["std", "alloc", "dlmalloc", "panic-hook-debug", "panic-hook-abort", "panic-hook"]
std = []
alloc = []
panic-hook = ["tezos-smart-rollup-panic-hook"]
panic-hook-debug = ["panic-hook", "tezos-smart-rollup-panic-hook/debug", "tezos-smart-rollup-debug/default"]
panic-hook-abort = ["panic-hook", "tezos-smart-rollup-panic-hook/abort"]
testing = []
