instructions:
  - set:
      value: 0000dc0a0713000c1e0200000000000000000000000000000000000000000000
      to: /evm/world_state/eth_accounts/6ce4d79d4e77402e1ef3417fdda433aa744c6e1c/balance
  - set:
      value: 0000dc0a0713000c1e0200000000000000000000000000000000000000000000
      to: /evm/world_state/eth_accounts/b53dc01974176e5dff2298c5a94343c2585e3c54/balance
  - set:
      value: 0000dc0a0713000c1e0200000000000000000000000000000000000000000000
      to: /evm/world_state/eth_accounts/9b49c988b5817be31dfb00f7a5a4671772dcce2b/balance
  - set:
      value: 0000dc0a0713000c1e0200000000000000000000000000000000000000000000
      to: /evm/world_state/eth_accounts/b2f428baf0916d30af9fb9801e2a648667a0a3da/balance
  - set:
      value: 0000dc0a0713000c1e0200000000000000000000000000000000000000000000
      to: /evm/world_state/eth_accounts/021df5394494cd3485b7b12646448a0dc923dd4a/balance
  - set:
      value: 0000dc0a0713000c1e0200000000000000000000000000000000000000000000
      to: /evm/world_state/eth_accounts/cdac74220da1399a78c3c850d2ca4b24ac4051e1/balance
  - set:
      # KT1FHqsvc7vRS3u54L66DdMX4gb6QKqxJ1JW
      value: 4B543146487173766337765253337535344C363644644D5834676236514B71784A314A57
      to: /evm/ticketer
