instructions:
  - set:
      # KT1DXADSWXucAJ6PujZeUSK9brpToFtC9fz6
      value: 4b5431445841445357587563414a3650756a5a6555534b39627270546f46744339667a36
      to: /evm/ticketer
  - set:
      value: 0000dc0a0713000c1e0200000000000000000000000000000000000000000000
      to: /evm/world_state/eth_accounts/6ce4d79d4e77402e1ef3417fdda433aa744c6e1c/balance
  - set:
      value: 0000dc0a0713000c1e0200000000000000000000000000000000000000000000
      to: /evm/world_state/eth_accounts/b53dc01974176e5dff2298c5a94343c2585e3c54/balance
  - set:
      value: 0000dc0a0713000c1e0200000000000000000000000000000000000000000000
      to: /evm/world_state/eth_accounts/9b49c988b5817be31dfb00f7a5a4671772dcce2b/balance
