# SPDX-FileCopyrightText: 2026 Nomadic-Labs <contact@nomadic-labs.com>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezosx-ethereum-runtime"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
alloy-primitives.workspace = true
primitive-types.workspace = true
revm-etherlink.workspace = true
thiserror.workspace = true
nom.workspace = true

tezosx-interfaces.workspace = true
tezos-evm-runtime.workspace = true
tezos-smart-rollup-host.workspace = true
tezos_data_encoding.workspace = true

[dev-dependencies]
