# SPDX-FileCopyrightText: 2023 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos-smart-rollup-installer-config"
version = "0.2.0"
edition = "2021"
authors = ["TriliTech <contact@trili.tech>"]
license = "MIT"
repository = "https://gitlab.com/tezos/tezos.git"
description = "Installer configuration for installer kernel of Tezos Smart Rollups."
keywords = ["tezos", "smart", "rollup", "installer", "config"]
categories = [
    "development-tools",
    "parser-implementations",
    "config",
    "no-std::no-alloc",
]

[dependencies.tezos-smart-rollup-host]
path = "../host"
version = "0.2.0"
default-features = false

[dependencies.tezos-smart-rollup-core]
path = "../core"
version = "0.2.0"
default-features = false

[dependencies.tezos-smart-rollup-encoding]
path = "../encoding"
version = "0.2.0"
default-features = false

[dependencies.nom]
version = "6.1"
default-features = false

[dependencies.tezos_data_encoding]
version = "0.5"
optional = true

[dependencies.serde]
version = "1.0"
optional = true
features = ["derive"]

[dependencies.serde_yaml]
version = "0.9"
optional = true

[dependencies.hex]
version = "0.4.3"
optional = true

[dependencies.tezos_crypto_rs]
version = "0.5"
default-features = false
optional = true

[dependencies.thiserror]
version = "1.0"
optional = true

[dev-dependencies.tezos-smart-rollup-mock]
path = "../mock"
version = "0.2.0"

[features]
default = ["std"]
std = ["alloc"]
alloc = [
    "tezos_data_encoding",
    "tezos-smart-rollup-host/alloc",
    "tezos-smart-rollup-encoding/alloc",
    "tezos-smart-rollup-encoding/tezos-encoding",
    "serde",
    "serde_yaml",
    "hex",
    "tezos_crypto_rs",
    "thiserror",
]
testing = []
