# SPDX-FileCopyrightText: 2023 Marigold <contact@marigold.dev>
# SPDX-FileCopyrightText: 2023 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "kernel-sequencer"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Sequencer framework for Tezos Smart Rollups"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies.tezos-smart-rollup-core]
path = "../kernel_sdk/core"
version = "0.2.0"
default-features = false

[dependencies.tezos-smart-rollup-host]
path = "../kernel_sdk/host"
version = "0.2.0"

[dev-dependencies.tezos-smart-rollup-mock]
path = "../kernel_sdk/mock"
version = "0.2.0"

[dependencies.tezos_data_encoding]
version = "0.5.2"

[dependencies.tezos_data_encoding_derive]
version = "0.5.2"

[dependencies.nom]
version = "7.1"

[dependencies.tezos_crypto_rs]
version = "0.5.0"
default-features = false

[dependencies.tezos-smart-rollup-encoding]
path = "../kernel_sdk/encoding"
version = "0.2.0"
default-features = false
features = ["alloc", "tezos-encoding", "crypto"]

[dependencies.tezos-smart-rollup-debug]
path = "../kernel_sdk/debug"
version = "0.2.0"

[dependencies.hex]
version = "0.4"

[dev-dependencies.tezos_crypto_rs]
version = "0.5.2"
default-features = false

[dev-dependencies.hex]
version = "0.4.3"

[features]
default = []

[[example]]
name = "sequenced_kernel"
crate-type = ["cdylib", "rlib"]
