# SPDX-FileCopyrightText: 2023 Marigold <contact@marigold.dev>
# SPDX-FileCopyrightText: 2022-2023 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos-smart-rollup-core"
edition = "2021"
version = "0.2.0"
license = "MIT"
authors = ["TriliTech <contact@trili.tech>"]
repository = "https://gitlab.com/tezos/tezos.git"
description = "Low-level host function definitions & constants for Tezos Smart Rollups."
keywords = ["tezos", "smart", "rollup"]
categories = ["no-std", "no-std::no-alloc", "api-bindings", "wasm"]

[dependencies]

[dependencies.mockall]
version = "0.11.0"
optional = true

[dev-dependencies.mockall]
version = "0.11.0"

[features]
"testing" = ["mockall"]
"proto-nairobi" = []
