# SPDX-FileCopyrightText: 2025 Functori <contact@functori.com>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos-execution-dionysus-r1"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]

tezos_crypto_rs.workspace = true
hex.workspace = true


tezos-evm-runtime.workspace = true
tezos-storage.workspace = true

tezos-smart-rollup-host.workspace = true
tezos_data_encoding.workspace = true

primitive-types.workspace = true
tezos-smart-rollup.workspace = true
