[package]
name = "tezos_data_encoding"
version = "0.6.0"
authors = ["TriliTech <contact@trili.tech>"]
edition = "2021"
rust-version = "1.64"
license = "MIT"
keywords = ["tezos"]
categories = ["encoding"]
description = "Utilities for encoding/decoding data compatible with tezos data encoding."
repository = "https://github.com/trilitech/tezedge.git"

[dependencies]
bit-vec = "0.6.2"
thiserror = "1.0"
hex = "0.4"
num-bigint = { version = "0.4", default-features = false, features = ["serde"] }
num-traits = "0.2.8"
serde = { version = "1.0", features = ["derive"] }
nom.workspace = true
bitvec = "1.0"
lazy_static = "1.4"

tezos_data_encoding_derive.workspace = true

[dev-dependencies]
serde_json = "1.0"
proptest = "1.1"

[features]
