# SPDX-FileCopyrightText: 2022-2023 TriliTech <contact@trili.tech>
# SPDX-FileCopyrightText: 2023 Nomadic Labs <contact@nomadic-labs.com>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos_smart_rollup_entrypoint"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
dlmalloc = { version = "0.2.3", features = ["global"], optional = true}

[dependencies.tezos_smart_rollup_core]
path = "../tezos_smart_rollup_core"
default-features = false

[dependencies.tezos_smart_rollup_panic_hook]
path = "../tezos_smart_rollup_panic_hook"
default-features = false
optional = true

[dependencies.tezos_smart_rollup_host]
path = "../tezos_smart_rollup_host"
default-features = false

[dependencies.tezos_smart_rollup_debug]
path = "../tezos_smart_rollup_debug"
default-features = false

[features]
default = ["std", "alloc", "dlmalloc", "panic-hook-debug", "panic-hook-abort"]
std = []
alloc = []
panic-hook = ["tezos_smart_rollup_panic_hook"]
panic-hook-debug = ["panic-hook", "tezos_smart_rollup_panic_hook/debug", "tezos_smart_rollup_debug/default"]
panic-hook-abort = ["panic-hook", "tezos_smart_rollup_panic_hook/abort"]
testing = []
