# SPDX-FileCopyrightText: 2022-2023 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos-smart-rollup-mock"
version = "0.2.1"
edition = "2021"
license = "MIT"
authors = ["TriliTech <contact@trili.tech>"]
repository = "https://gitlab.com/tezos/tezos.git"
description = "Mock implementation of Tezos Smart Rollup host functions to enable unit testing of kernel logic."
keywords = ["tezos", "smart", "rollup"]
categories = ["development-tools", "development-tools::testing"]

[dependencies]
hex = "0.4"
tezos_crypto_rs = { version = "0.5.2", default-features = false }
tezos_data_encoding = "0.5.2"

[dependencies.tezos-smart-rollup-encoding]
path = "../encoding"
version = "0.2.1"
default-features = false
features = ["alloc", "tezos-encoding", "crypto"]

[dependencies.tezos-smart-rollup-core]
path = "../core"
version = "0.2.1"

[dependencies.tezos-smart-rollup-host]
path = "../host"
version = "0.2.1"

[dev-dependencies.tezos-smart-rollup-host]
path = "../host"
version = "0.2.1"
features = ["default"]

[features]
proto-nairobi = ["tezos-smart-rollup-core/proto-nairobi", "tezos-smart-rollup-host/proto-nairobi"]
proto-alpha = ["tezos-smart-rollup-core/proto-alpha", "tezos-smart-rollup-host/proto-alpha"]
