[workspace]
resolver = "2"
members = [
  # Libraries
  "kernel_loader",
  "interpreter",
  "pvm",
  "api",
  # Executables
  "sandbox",
]
exclude = ["jstz", "dummy_kernel", "tests"]

[workspace.dependencies]
rustc_apfloat = "0.2.0"
ieee-apsqrt = "0.1.1"
