# SPDX-FileCopyrightText: 2026 Nomadic-Labs <contact@nomadic-labs.com>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezosx-interfaces"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
tezos-evm-runtime.workspace = true
primitive-types.workspace = true

[dev-dependencies]
