# SPDX-FileCopyrightText: 2024 Functori <contact@functori.com>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos-storage-dionysus-r1"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
thiserror.workspace = true
anyhow.workspace = true

primitive-types.workspace = true

rlp.workspace = true
hex.workspace = true

tezos_crypto_rs.workspace = true
sha3.workspace = true

tezos_ethereum.workspace = true
tezos-evm-runtime.workspace = true
tezos-smart-rollup-host.workspace = true
tezos-smart-rollup-storage.workspace = true
