# SPDX-FileCopyrightText: 2022-2024 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "tx_kernel"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nom = "7.1"
thiserror = "1.0"
hex = "0.4"
num-bigint = { version = "0.4", default-features = false }
num-traits = "0.2.8"

tezos_data_encoding.workspace = true
tezos_crypto_rs.workspace = true
tezos-protocol.workspace = true

# Adding these to 'dev_dependencies' causes the rand feature in crypto to be enabled
# on wasm builds, when building the entire workspace.
rand = { version = "0.8", optional = true }
proptest = { version = "1.0", optional = true }

tezos-smart-rollup.workspace = true
tezos-smart-rollup-core.workspace = true
tezos-smart-rollup-host.workspace = true
tezos-smart-rollup-debug.workspace = true
tezos-smart-rollup-entrypoint.workspace = true
tezos-smart-rollup-storage.workspace = true
tezos-smart-rollup-encoding.workspace = true
tezos-smart-rollup-mock.workspace = true

[features]
default = ["tx-kernel"]
dal = [
  "proto-alpha",
]
proto-alpha = [
  "tezos-smart-rollup/proto-alpha",
  "tezos-smart-rollup-core/proto-alpha",
  "tezos-smart-rollup-host/proto-alpha",
  "tezos-smart-rollup-mock/proto-alpha",
  "tezos-smart-rollup-encoding/proto-alpha",
]
debug = []
testing = [
  "rand",
  "proptest",
  "tezos-smart-rollup-core/mock-core-trait",
  "tezos-smart-rollup-encoding/testing",
  "tezos_crypto_rs/std",
]
tx-kernel = []
tx-kernel-no-sig-verif = ["tx-kernel"]
