# SPDX-FileCopyrightText: 2025 Functori <contact@functori.com>
#
# SPDX-License-Identifier: MIT

[package]
name = 'revm-evaluation'
version = '0.1.0'
edition = '2021'
license = "MIT"

[dependencies]
# Workspace deps
revm-etherlink.workspace = true
revm.workspace = true
serde.workspace = true
primitive-types.workspace = true # TODO: temporary, should be dropped once [evm_execution] is deprecated.
tezos_ethereum.workspace = true
tezos-evm-logging.workspace = true
tezos-evm-runtime.workspace = true
tezos-smart-rollup-host.workspace = true
tezos-smart-rollup-core.workspace = true
tezosx-interfaces.workspace = true

kernel.workspace = true

# Evaluation specific deps
serde_json = { version = "1.0.145", features = ["preserve_order"] }
structopt = "0.3.26"

[features]
default = []
disable-file-logs = []
