# SPDX-FileCopyrightText: 2023 TriliTech <contact@trili.tech>
# SPDX-FileCopyrightText: 2023 Nomadic Labs <contact@nomadic-labs.com>
# SPDX-FileCopyrightText: 2023 Marigold <contact@marigold.dev>
# SPDX-FileCopyrightText: 2023 Functori <contact@functori.com>
#
# SPDX-License-Identifier: MIT

[package]
name = "evm-execution"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]

thiserror.workspace = true

num-bigint.workspace = true
num-traits.workspace = true
primitive-types.workspace = true

hex.workspace = true
rlp.workspace = true
const-decoder.workspace = true

tezos_crypto_rs.workspace = true
sha2.workspace = true
sha3.workspace = true
ripemd.workspace = true
libsecp256k1.workspace = true

evm.workspace = true

tezos_ethereum.workspace = true
tezos-evm-logging.workspace = true

tezos-smart-rollup-core.workspace = true
tezos-smart-rollup-host.workspace = true
tezos-smart-rollup-debug.workspace = true
tezos-smart-rollup-encoding.workspace = true
tezos-smart-rollup-storage.workspace = true

# Adding these to 'dev_dependencies' causes the rand feature in crypto to be enabled
# on wasm builds, when building the entire workspace.
rand = { workspace = true, optional = true }
proptest = { workspace = true, optional = true }

[dev-dependencies]
tezos-smart-rollup-mock.workspace = true
tezos_data_encoding.workspace = true

[features]
default = ["evm_execution"]
testing = ["rand", "proptest"]
evm_execution = []
debug = []
# the `benchmark` feature flag instruments the kernel for profiling
benchmark = ["debug"]
