# SPDX-FileCopyrightText: 2023 Nomadic Labs <contact@nomadic-labs.com>
# SPDX-FileCopyrightText: 2023 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = 'evm_kernel'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ["cdylib"]

[dependencies.tezos_smart_rollup_core]
path = "../../kernel_sdk/tezos_smart_rollup_core"

[dependencies.tezos_smart_rollup_host]
path = "../../kernel_sdk/tezos_smart_rollup_host"

[dependencies.tezos_smart_rollup_panic_hook]
path = "../../kernel_sdk/tezos_smart_rollup_panic_hook"

[dependencies.tezos_smart_rollup_entrypoint]
path = "../../kernel_sdk/tezos_smart_rollup_entrypoint"

[dependencies.tezos_smart_rollup_debug]
path = "../../kernel_sdk/tezos_smart_rollup_debug"

[dev-dependencies.tezos_smart_rollup_encoding]
path = "../../kernel_sdk/tezos_smart_rollup_encoding"

[dev-dependencies.tezos_smart_rollup_mock]
path = "../../kernel_sdk/tezos_smart_rollup_mock"

[dependencies]
tezos_ethereum = { path = "../ethereum" }
primitive-types = { version = "0.11.1", default-features = false }
hex = "0.4"
num-traits = "0.2.8"
clarity = { version = "0.7.0", default-features = false }

[features]
default = ["panic-hook"]
panic-hook = []
