# SPDX-FileCopyrightText: 2023 Nomadic Labs <contact@nomadic-labs.com>
# SPDX-FileCopyrightText: 2023 TriliTech <contact@trili.tech>
# SPDX-FileCopyrightText: 2023 Functori <contact@functori.com>
#
# SPDX-License-Identifier: MIT

[package]
name = 'evm_kernel'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ["cdylib"]

[dependencies.tezos-smart-rollup-core]
path = "../../kernel_sdk/core"
features = ["proto-nairobi"]

[dependencies.tezos-smart-rollup-host]
path = "../../kernel_sdk/host"
features = ["proto-nairobi"]

[dependencies.tezos-smart-rollup-panic-hook]
path = "../../kernel_sdk/panic-hook"

[dependencies.tezos-smart-rollup-entrypoint]
path = "../../kernel_sdk/entrypoint"

[dependencies.tezos-smart-rollup-debug]
path = "../../kernel_sdk/debug"

[dependencies.tezos-smart-rollup-encoding]
path = "../../kernel_sdk/encoding"

[dependencies.installer-kernel]
path = "../../kernel_sdk/installer-kernel"

[dependencies.tezos-smart-rollup-installer-config]
path = "../../kernel_sdk/installer-config"

[dependencies.tezos-smart-rollup-installer]
path = "../../kernel_sdk/installer-client"

[dev-dependencies.tezos-smart-rollup-mock]
path = "../../kernel_sdk/mock"
features = ["proto-nairobi"]

[dev-dependencies.tezos_data_encoding]
version = "0.5"

[dependencies]
tezos_ethereum = { path = "../ethereum" }
primitive-types = { version = "0.11.1", default-features = false }
hex = "0.4"
hex-literal = "0.4.1"
num-traits = "0.2.8"
evm-execution = { path = "../evm_execution" }
rlp = "0.5.2"
sha3 = { version = "0.10.6", default-features = false }
libsecp256k1 = { version = "0.7", default-features = false, features = ["static-context", "hmac"] }

[features]
default = ["panic-hook"]
panic-hook = []
