# SPDX-FileCopyrightText: 2023 Nomadic Labs <contact@nomadic-labs.com>
# SPDX-FileCopyrightText: 2023 Marigold <contact@marigold.dev>
# SPDX-FileCopyrightText: 2026 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[workspace]
resolver = "2"
members = ["kernel", "collector"]

[workspace.dependencies]
tezos-smart-rollup = { path = "../kernel_sdk/sdk" }
tezos-smart-rollup-core = { path = "../kernel_sdk/core" }
tezos-smart-rollup-host = { path = "../kernel_sdk/host" }
tezos-smart-rollup-debug = { path = "../kernel_sdk/debug" }
tezos-smart-rollup-entrypoint = { path = "../kernel_sdk/entrypoint" }
tezos-smart-rollup-storage = { path = "../kernel_sdk/storage" }
tezos-smart-rollup-encoding = { path = "../kernel_sdk/encoding" }
tezos-smart-rollup-mock = { path = "../kernel_sdk/mock" }
tezos_data_encoding = { path = "../../sdk/rust/encoding" }
tezos_crypto_rs = { path = "../../sdk/rust/crypto", default-features = false }
tezos-protocol = { path = "../../sdk/rust/protocol" }
