# SPDX-FileCopyrightText: 2023-2025 Nomadic Labs <contact@nomadic-labs.com>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos-evm-logging-farfadet-r2"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
num-traits.workspace = true
num-derive.workspace = true
tezos-smart-rollup-debug.workspace = true
tezos-smart-rollup-host.workspace = true
nop-macros.workspace = true
tracing = { workspace = true, optional = true }

[features]
default = ["alloc"]
alloc = []
debug = []
benchmark = []
tracing = ["dep:tracing"]
