# If you modify this file, generate the lock file using `poetry lock`.
[tool.poetry]
name = "tezos-b58"
version = "0.1.0"
description = "Script to generate bytes prefixes for base58 encoding given a payload."

readme = "README.md"

authors = [
  "Tezos community <tezos@tezos.com>"
]
repository = "https://gitlab.com/tezos/tezos"
homepage = "https://gitlab.com/tezos/tezos"

keywords = ["tezos"]


[tool.poetry.dependencies]
python = "^3.9"
base58 = "*"
fire = "*"
pylint = "*"
pytest = "*"