# If you modify this file, generate the lock file using `poetry lock` and copy
# the resulting poetry.lock file with this one in https://gitlab.com/tezos/opam-repository
[tool.poetry]
name = "tezos-python-integration-tests"
version = "0.1.0"
description = "Python tests suites for Tezos"

readme = "README.md"

authors = [
  "Tezos community <tezos@tezos.com>"
]
repository = "https://gitlab.com/tezos/tezos"
homepage = "https://gitlab.com/tezos/tezos"

keywords = ["tezos"]


[tool.poetry.dependencies]
python = "~3.8"

base58check = "1.0.2"
ed25519 = "1.4"
# Set to 0.790 because the tests replication give duplicated modules errors with
# mypy >= 0.8.
# Replace with `mypy = "*"` when the tests have been refactorized.
mypy = "0.790"
mypy-extensions = "*"
pyblake2 = "1.1.2"
pycryptodome = "3.9.7"
pycodestyle = "*"
py_ecc = "2.0.0"
pylint = "*"
pytest = "*"
pytest-regtest = { "git" = "https://gitlab.com/nomadic-labs/pytest-regtest", branch="fc5bd9b2" }
pytest-timeout = "*"
requests = "*"
black = "^20.8b1"
# Used to validate the OpenAPI spec.
openapi-spec-validator = "0.2.9"

[tool.black]
line-length = 80
skip-string-normalization = true