[package]
name = "octez-libcrux-ml-dsa"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "cdylib"]

[lints.clippy]
allow_attributes = "deny"
allow_attributes_without_reason = "deny"

[lints.rustdoc]
broken_intra_doc_links = "deny"
private_intra_doc_links = "allow"

[dependencies]
zeroize = "1.8"

[dependencies.libcrux-ml-dsa]
version = "0.0.5"
default-features = false
features = ["mldsa44"]

[dependencies.ocaml]
version = "1.2.1"
default-features = false

[dependencies.ocaml-sys]
# We don't care about the version. Ideally this gets pinned to what `ocaml` needs.
version = "*"
default-features = false

[dependencies.ocaml-boxroot-sys]
# We don't care about the version. Ideally this gets pinned to what `ocaml` needs.
version = "*"
default-features = false

[build-dependencies]
ocaml-build = "1.0.0"

[features]
default = ["ocaml/default"]