[package]
name = "risc-v-dummy-bm"
version = "0.0.0"
edition = "2021"

[dependencies.riscv-rt]
version = "*"
optional = true

[dependencies.tezos-smart-rollup-panic-hook]
path = "../../kernel_sdk/panic-hook"
version = "0.2.2"
default-features = false

[dependencies.tezos-smart-rollup]
path = "../../kernel_sdk/sdk"
version = "0.2.2"
default-features = false
features = ["debug_alloc", "proto-alpha-no-mock"]

[features]
default = ["bare-metal"]
bare-metal = ["riscv-rt"]
