[package]
name = "risc-v-interpreter"
version = "0.0.0"
edition = "2021"

[dependencies]
derive_more = "0.99.17"
num_enum = "0.7.2"
paste = "1.0.14"
thiserror = "1.0.57"

[dependencies.strum]
version = "0.26.1"
features = ["derive"]

[dev-dependencies]
goblin = "0.7.1"
hex = "0.4.3"
rand = "0.8.5"
proptest = "1.4.0"
